- id: pyright-conda
  name: pyright-conda
<<<<<<< before updating
  description: Python command line wrapper for pyright, a static type checker
=======
  description: 'This hook runs pyright.'
>>>>>>> after updating
  entry: pyright
  language: conda
  types: [python]
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: '2.9.2'
