-   id: pyright-conda
    name: pyright-conda
    description: 'Python command line wrapper for pyright, a static type checker'
    entry: pyright
    language: conda
    types: [python]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
